# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cac7c975c928c12e96ba52361d9309551fb236b71a11906f9e161b56b69dc5cf6c3060b4ed255e7f044bddae8f3b48e0dafb1fdc8be1803fddb4edc9e1972ce2

test:
  secret_key_base: 0f79792095e36b50469d8f1f2b7772658468dd4e74efa26b4d69672bc8ee32b82d17c3c9b9a6d5284ef0a7a918fc0e17c7afbce22ea084b9abeb78cd5cdf0516

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
